service: sheeee
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  profile: admin
  region: ap-southeast-1

functions:
  function1:
    handler: ./src/index.handler
  createUser:
    handler: ./src/users/create.createUser
    events:
      - http:
          path: /users/{id}
          method: post
